alter table public.orders
  add column if not exists inventory_item_id bigint references public.inventory_items(id);

alter table public.products
  add column if not exists inventory_item_id bigint references public.inventory_items(id);

create table if not exists public.inventory_usage_events (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id),
  inventory_item_id bigint references public.inventory_items(id),
  quantity_planned integer not null default 0,
  quantity_deducted integer not null default 0,
  deduction_status text not null default 'pending',
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists orders_inventory_item_id_idx
  on public.orders (inventory_item_id);

create index if not exists products_inventory_item_id_idx
  on public.products (inventory_item_id);

create index if not exists inventory_usage_events_order_id_idx
  on public.inventory_usage_events (order_id);
