create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  item_name text not null,
  category text,
  vendor text,
  material text,
  color text,
  size text,
  quantity_on_hand integer not null default 0,
  reorder_level integer not null default 0,
  unit_cost numeric(10, 2) not null default 0,
  storage_location text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists inventory_items_sku_idx
  on public.inventory_items (sku);

create index if not exists inventory_items_category_idx
  on public.inventory_items (category);
