create table if not exists public.receiving_orders (
  id bigint generated by default as identity primary key,
  vendor text,
  purchase_order_number text,
  item_name text not null,
  sku text not null,
  quantity_ordered integer not null default 0,
  quantity_received integer not null default 0,
  unit_cost numeric(10, 2) not null default 0,
  order_date date,
  expected_delivery_date date,
  received_date date,
  status text not null default 'Ordered',
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists receiving_orders_sku_idx
  on public.receiving_orders (sku);

create index if not exists receiving_orders_status_idx
  on public.receiving_orders (status);

create index if not exists receiving_orders_vendor_idx
  on public.receiving_orders (vendor);
