create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  vendor_name text not null,
  website text,
  contact_name text,
  email text,
  phone text,
  product_categories text,
  notes text,
  preferred_vendor boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists vendors_vendor_name_idx
  on public.vendors (vendor_name);

create index if not exists vendors_preferred_vendor_idx
  on public.vendors (preferred_vendor);
